## 应用名称
#spring.application.name=demo
## 应用服务 WEB 访问端口
#server.port=8080
#taco.order.id= 1
#taco.order.userName=hf
#taco.order.note=1234
server:
  port: 8080
taco:
  order:
    id: 123456789
    userName: hf
    note: 123
spring:
  redis:
    database: 0
    host: 192.168.1.100
    port: 6379
    timeout: 6000
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5






